
spring:
  datasource:
    url: jdbc:mysql://120.48.108.48:3306/supplier
    username: root
    password: 123456
    hikari:
        minimum-idle: 10
        maximum-pool-size: 20
        # 客户端最大等待时间
        connection-timeout: 60000
  redis:
    database: 0
    host: 120.48.108.48
    port: 6379
    username: redis
    password: redis
    timeout: 5000
#    lettuce:
#      pool:
#        max-active: 100
#        min-idle: 10
#        max-idle: 50
  #    password: redis
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos 服务地址
#      discovery:
#        namespace: 40df6308-4b8a-4ff1-94d2-283cf66d0a33

logging:
  level:
    # 日志级别 debug>info>warn>error
    com.lhd.qd: debug

web:
  jwt:
    url: /api/**
    login-url: /api/login
    secret: secret
    expiration: 604800000
    header: Jwt-Authorization



sms:
  apiUrl: https://sms_developer.zhenzikj.com
  appId: 112192
  appSecret: 4e530e58-6284-43fd-8a4d-b95372f473a6
  timeOut: 3
  codeLength: 6