
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qd_admin
    username: root
    password: aA@123456
    hikari:
        minimum-idle: 10
        maximum-pool-size: 20
        # 客户端最大等待时间
        connection-timeout: 60000
  redis:
    database: 15
    host: localhost
    port: 6379
    password:
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos 服务地址
      discovery:
        namespace: cloud
logging:
  level:
    # 日志级别 debug>info>warn>error
    com.lhd.qd: debug


web:
  jwt:
    url: /api/**
    login-url: /api/login
    secret: secret
    expiration: 604800000
    header: Jwt-Authorization